### ISSUE TITLE
Error installing new version of ktext

### ISSUE THREAD

**Issue by johnhaley81** [hamelsmu/ktext#7]
I tried to test out #3 but I got some console errors doing both `pip3 install --upgrade ktext` and  removing and running `pip3 install ktext`.

Here's my console output:

```
Collecting ktext
  Downloading ktext-0.31.tar.gz
Requirement already up-to-date: numpy in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from ktext)
Requirement already up-to-date: scipy in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from ktext)
Requirement already up-to-date: six in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from ktext)
Requirement already up-to-date: pandas>=0.21.0 in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from ktext)
Requirement already up-to-date: pyyaml in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from ktext)
Requirement already up-to-date: pathos in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from ktext)
Requirement already up-to-date: msgpack in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from ktext)
Collecting msgpack_numpy (from ktext)
  Downloading msgpack_numpy-0.4.2-py2.py3-none-any.whl
Requirement already up-to-date: dask in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from ktext)
Requirement already up-to-date: pyarrow in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from ktext)
Collecting more_itertools (from ktext)
  Downloading more_itertools-4.1.0-py3-none-any.whl (47kB)
    100% |################################| 51kB 5.2MB/s
Requirement already up-to-date: textacy in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from ktext)
Requirement already up-to-date: keras in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from ktext)
Requirement already up-to-date: pytz>=2011k in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from pandas>=0.21.0->ktext)
Requirement already up-to-date: python-dateutil>=2 in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from pandas>=0.21.0->ktext)
Requirement already up-to-date: ppft>=1.6.4.7 in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from pathos->ktext)
Requirement already up-to-date: dill>=0.2.7 in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from pathos->ktext)
Requirement already up-to-date: pox>=0.2.3 in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from pathos->ktext)
Requirement already up-to-date: multiprocess>=0.70.5 in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from pathos->ktext)
Requirement already up-to-date: msgpack-python>=0.3.0 in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from msgpack_numpy->ktext)
Requirement already up-to-date: ftfy<5.0.0,>=4.2.0 in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from textacy->ktext)
Requirement already up-to-date: unidecode>=0.04.19 in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from textacy->ktext)
Requirement already up-to-date: python-levenshtein>=0.12.0 in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from textacy->ktext)
Requirement already up-to-date: requests>=2.10.0 in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from textacy->ktext)
Requirement already up-to-date: scikit-learn>=0.17.0 in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from textacy->ktext)
Requirement already up-to-date: spacy>=2.0.0 in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from textacy->ktext)
Requirement already up-to-date: cachetools>=2.0.0 in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from textacy->ktext)
Requirement already up-to-date: tqdm>=4.11.1 in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from textacy->ktext)
Requirement already up-to-date: pyphen>=0.9.4 in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from textacy->ktext)
Requirement already up-to-date: ijson>=2.3 in /srv/.pyenv/versions/3.6.3/lib/python3.6/site-packages (from textacy->ktext)
Collecting networkx>=1.11 (from textacy->ktext)
  Downloading networkx-2.1.zip (1.6MB)
    100% |################################| 1.6MB 803kB/s
Collecting cytoolz>=0.8.0 (from textacy->ktext)
  Downloading cytoolz-0.9.0.tar.gz (443kB)
    100% |################################| 450kB 2.5MB/s
Collecting pyemd>=0.3.0 (from textacy->ktext)
  Downloading pyemd-0.5.0.tar.gz (91kB)
    100% |################################| 92kB 4.9MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-2t_bhkrj/pyemd/setup.py", line 87, in <module>
        README = f.read()
      File "/srv/.pyenv/versions/3.6.3/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2247: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2t_bhkrj/pyemd/
```

This seems like it's really an issue with pyemd so I created https://github.com/wmayner/pyemd/issues/27 but I figured I'd make one here as well so you would know about it.

**Comment by hamelsmu** [comment]
@johnhaley81 thanks for letting me know!  Did you eventually get this working?  

Please let me know if you have any other feedback.
